// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpapi

// Defines values for ProblemCode.
const (
	ProblemCodeAuthenticationRequired    ProblemCode = "authentication_required"
	ProblemCodeAuthenticationUnavailable ProblemCode = "authentication_unavailable"
	ProblemCodeAuthorizationForbidden    ProblemCode = "authorization_forbidden"
	ProblemCodeInternalError             ProblemCode = "internal_error"
	ProblemCodeInvalidPlayerTag          ProblemCode = "invalid_player_tag"
	ProblemCodeInvalidRequest            ProblemCode = "invalid_request"
	ProblemCodeMethodNotAllowed          ProblemCode = "method_not_allowed"
	ProblemCodePlayerNotFound            ProblemCode = "player_not_found"
	ProblemCodeProviderMisconfigured     ProblemCode = "provider_misconfigured"
	ProblemCodeProviderRateLimited       ProblemCode = "provider_rate_limited"
	ProblemCodeProviderUnavailable       ProblemCode = "provider_unavailable"
	ProblemCodeReauthenticationRequired  ProblemCode = "reauthentication_required"
	ProblemCodeResourceNotFound          ProblemCode = "resource_not_found"
	ProblemCodeSemanticValidationFailed  ProblemCode = "semantic_validation_failed"
	ProblemCodeVersionConflict           ProblemCode = "version_conflict"
)

// Valid indicates whether the value is a known member of the ProblemCode enum.
func (e ProblemCode) Valid() bool {
	switch e {
	case ProblemCodeAuthenticationRequired:
		return true
	case ProblemCodeAuthenticationUnavailable:
		return true
	case ProblemCodeAuthorizationForbidden:
		return true
	case ProblemCodeInternalError:
		return true
	case ProblemCodeInvalidPlayerTag:
		return true
	case ProblemCodeInvalidRequest:
		return true
	case ProblemCodeMethodNotAllowed:
		return true
	case ProblemCodePlayerNotFound:
		return true
	case ProblemCodeProviderMisconfigured:
		return true
	case ProblemCodeProviderRateLimited:
		return true
	case ProblemCodeProviderUnavailable:
		return true
	case ProblemCodeReauthenticationRequired:
		return true
	case ProblemCodeResourceNotFound:
		return true
	case ProblemCodeSemanticValidationFailed:
		return true
	case ProblemCodeVersionConflict:
		return true
	default:
		return false
	}
}

// BootstrapStatus defines model for BootstrapStatus.
type BootstrapStatus struct {
	// Stage Example: bootstrap
	Stage string `json:"stage"`

	// Status Example: ready
	Status string `json:"status"`
}

// ProblemCode Stable non-sensitive application error code.
type ProblemCode string

// ProblemDetails RFC 9457 problem. Never contains tokens, Firebase UIDs, Player Tags, external URLs, raw payloads, stack traces or infrastructure detail.
type ProblemDetails struct {
	// Code Stable non-sensitive application error code.
	Code   ProblemCode `json:"code"`
	Status int         `json:"status"`
	Title  string      `json:"title"`

	// TraceId Correlation identifier for support; never a secret.
	TraceId string `json:"traceId"`

	// Type Example: https://www.rfc-editor.org/rfc/rfc9457
	Type string `json:"type"`
}

// Forbidden RFC 9457 problem. Never contains tokens, Firebase UIDs, Player Tags, external URLs, raw payloads, stack traces or infrastructure detail.
type Forbidden = ProblemDetails

// InternalError RFC 9457 problem. Never contains tokens, Firebase UIDs, Player Tags, external URLs, raw payloads, stack traces or infrastructure detail.
type InternalError = ProblemDetails

// Unauthorized RFC 9457 problem. Never contains tokens, Firebase UIDs, Player Tags, external URLs, raw payloads, stack traces or infrastructure detail.
type Unauthorized = ProblemDetails
