/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reports that the authenticated application foundation is running. */
        get: operations["getBootstrapStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Deletes the caller's CrownPilot data (planned).
         * @description Planned contract; the route is not implemented yet and currently answers 404. Removes only CrownPilot data, never the Firebase/Google account. Requires an `auth_time` within 5 minutes (60 seconds tolerance) and a Firebase revocation check; if Firebase cannot be reached during that check the request fails closed with 503 `authentication_unavailable`.
         */
        delete: operations["deleteMe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BootstrapStatus: {
            /** @example ready */
            status: string;
            /** @example bootstrap */
            stage: string;
        };
        /** @description RFC 9457 problem. Never contains tokens, Firebase UIDs, Player Tags, external URLs, raw payloads, stack traces or infrastructure detail. */
        ProblemDetails: {
            /** @example https://www.rfc-editor.org/rfc/rfc9457 */
            type: string;
            title: string;
            status: number;
            code: components["schemas"]["ProblemCode"];
            /** @description Correlation identifier for support; never a secret. */
            traceId: string;
        };
        /**
         * @description Stable non-sensitive application error code.
         * @enum {string}
         */
        ProblemCode: "invalid_request" | "authentication_required" | "authorization_forbidden" | "resource_not_found" | "method_not_allowed" | "invalid_player_tag" | "player_not_found" | "version_conflict" | "semantic_validation_failed" | "provider_rate_limited" | "provider_unavailable" | "provider_misconfigured" | "authentication_unavailable" | "reauthentication_required" | "internal_error";
    };
    responses: {
        /** @description Bearer token is absent or invalid. */
        Unauthorized: {
            headers: {
                "WWW-Authenticate"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Authenticated subject is not authorized. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Unexpected failure; generic message with traceId. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getBootstrapStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The foundation is running. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CrownPilot data removed, or nothing to remove (idempotent). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            /** @description The authenticated subject is not authorized, or must sign in again (`reauthentication_required`). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            500: components["responses"]["InternalError"];
            /** @description Firebase could not be reached during the sensitive revocation check. Generic problem without provider detail; distinct from `provider_unavailable`, which is reserved for the Clash Royale lookup. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
